baseurl = "https://engboustani.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Hossein Boustani"
disqusshortname = ""
pluralizelisttitles = false
title = "Hossein Boustani Personal Blog"

[permalinks]
    blog = "blog/:slug/"

[params]
    dateform = "Jan 2, 2006"
    dateformfull = "Mon Jan 2 2006 15:04:05 MST"
    description = "A notebook from a developer for developers"
    copyright = "Copyright © 2019 Hossein Boustani"
    highlightjs = true
    progressively = true
    align_left = false
    lang = "en"
    github = "engboustani"
    email = "eng.boustani@gmail.com"
    linkedin = "engboustani"
    twitter = "engboustani"
    posts_navigation = true
    small_banner_logo = false
    logofile = "./resources/_gen/images/logo.jpg"